#!/bin/sh

set -e

GROUP="eviacam"

. /usr/share/debconf/confmodule

#DEBHELPER#

case "$1" in
	purge)
		if sg "$GROUP" true 2>/dev/null; then
			delgroup --quiet --only-if-empty "$GROUP" >/dev/null 2>&1 || true
		fi
		;;	
	*)
		;;
esac

